### ISSUE TITLE
Is countries.js should change as locations.js?

### ISSUE THREAD

**Issue by aligoren** [kodilan-com/frontend#1]
I thought this because countries contain only cities. I found CountrySelect.vue file that imports countries.js.

**countries.js**

https://github.com/kodilan-com/frontend/blob/master/src/assets/data/countries.js

**CountrySelect.vue**

https://github.com/kodilan-com/frontend/blob/b4bf5d5763329ff2551820ef8599c28db4734990/src/components/shared/CountrySelect.vue

Anyway, if this data file will not contain any real county name, I think its name should be locations.js.

There is another reason to think about that. Almost all variable names contain the location word.

https://github.com/kodilan-com/frontend/blob/b4bf5d5763329ff2551820ef8599c28db4734990/src/components/shared/CountrySelect.vue#L16-L46

**Comment by fatihacet** [comment]
Haha 😄 Right, they are not countries, they are cities :) and it also has "Remote" so naming it as cities also doesn't make sense. It should be locations.

I actually deleted it [in this commit](https://github.com/kodilan-com/frontend/commit/d6fb56cf2d6fe04a7cd665cd051bcfdf4b6ee4dd) and I needed to [bring it back](https://github.com/kodilan-com/frontend/commit/c8bfaba80bfd4217e3359c00bc8f32bfdbb04f1c) because of the Add New Job page. 

Feel free to submit a PR for this change.
